export const corporateAssetStatements = [
  `CREATE TABLE IF NOT EXISTS departments (
    id TEXT PRIMARY KEY,
    department_code TEXT NOT NULL UNIQUE,
    department_name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS employees (
    id TEXT PRIMARY KEY,
    employee_code TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    department_id TEXT REFERENCES departments(id),
    base_station_id TEXT REFERENCES stations(id),
    position_title TEXT NOT NULL,
    employment_status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (employment_status IN ('ACTIVE', 'INACTIVE')),
    demo_actor_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS managed_assets (
    id TEXT PRIMARY KEY,
    asset_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('GSE', 'VEHICLE', 'IT_EQUIPMENT', 'MACHINERY', 'FACILITY', 'FURNITURE', 'OTHER')),
    brand TEXT,
    model TEXT,
    serial_number TEXT,
    station_id TEXT REFERENCES stations(id),
    location_type TEXT NOT NULL CHECK (location_type IN ('STATION', 'DEPARTMENT', 'TRANSIT', 'VENDOR', 'UNASSIGNED', 'RETIRED', 'LOST')),
    location_detail TEXT NOT NULL,
    department_id TEXT REFERENCES departments(id),
    current_custodian_employee_id TEXT REFERENCES employees(id),
    custodian_name_snapshot TEXT,
    acquisition_date TEXT,
    acquisition_reference TEXT,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (lifecycle_status IN ('ACTIVE', 'RETIRED', 'DISPOSED', 'LOST')),
    condition_status TEXT NOT NULL DEFAULT 'SERVICEABLE' CHECK (condition_status IN ('SERVICEABLE', 'LIMITED', 'UNDER_MAINTENANCE', 'UNSERVICEABLE')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_managed_assets_serial ON managed_assets(serial_number) WHERE serial_number IS NOT NULL AND serial_number <> ''`,
  `CREATE INDEX IF NOT EXISTS idx_managed_assets_station ON managed_assets(station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_managed_assets_status ON managed_assets(lifecycle_status, condition_status)`,
  `CREATE TABLE IF NOT EXISTS asset_number_sequences (
    sequence_type TEXT PRIMARY KEY,
    current_value INTEGER NOT NULL CHECK (current_value >= 0)
  )`,
  `CREATE TABLE IF NOT EXISTS asset_assignments (
    id TEXT PRIMARY KEY,
    assignment_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    employee_id TEXT REFERENCES employees(id),
    custodian_name_snapshot TEXT NOT NULL,
    department_id TEXT REFERENCES departments(id),
    station_id TEXT REFERENCES stations(id),
    location_snapshot TEXT NOT NULL,
    reason TEXT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    created_by_user_id TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_asset_active_assignment ON asset_assignments(asset_id) WHERE ended_at IS NULL`,
  `CREATE TABLE IF NOT EXISTS asset_custody_movements (
    id TEXT PRIMARY KEY,
    movement_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    from_station_id TEXT REFERENCES stations(id),
    to_station_id TEXT REFERENCES stations(id),
    from_location TEXT NOT NULL,
    to_location TEXT NOT NULL,
    to_location_type TEXT NOT NULL,
    new_employee_id TEXT REFERENCES employees(id),
    new_custodian_name_snapshot TEXT,
    reason TEXT NOT NULL,
    moved_by_user_id TEXT NOT NULL,
    moved_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS asset_maintenance_work_orders (
    id TEXT PRIMARY KEY,
    work_order_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    maintenance_type TEXT NOT NULL CHECK (maintenance_type IN ('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY')),
    priority TEXT NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'CANCELLED')),
    condition_before TEXT NOT NULL,
    condition_after TEXT,
    summary TEXT NOT NULL,
    completion_result TEXT,
    scheduled_at TEXT,
    completed_at TEXT,
    completed_by_user_id TEXT,
    created_by_user_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_asset_maintenance_asset ON asset_maintenance_work_orders(asset_id, status)`,
  `CREATE TABLE IF NOT EXISTS asset_insurance_policies (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    insurer TEXT NOT NULL,
    policy_number TEXT NOT NULL UNIQUE,
    coverage_minor INTEGER NOT NULL DEFAULT 0 CHECK (coverage_minor >= 0),
    premium_minor INTEGER NOT NULL DEFAULT 0 CHECK (premium_minor >= 0),
    effective_date TEXT NOT NULL,
    expiry_date TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS asset_audits (
    id TEXT PRIMARY KEY,
    audit_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    auditor_employee_id TEXT REFERENCES employees(id),
    auditor_name_snapshot TEXT NOT NULL,
    audited_at TEXT NOT NULL,
    notes TEXT,
    has_discrepancy INTEGER NOT NULL DEFAULT 0,
    reconciled_at TEXT,
    reconciled_by_user_id TEXT,
    reconciliation_reason TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS asset_audit_lines (
    id TEXT PRIMARY KEY,
    audit_id TEXT NOT NULL REFERENCES asset_audits(id) ON DELETE CASCADE,
    field_name TEXT NOT NULL,
    expected_value TEXT,
    actual_value TEXT,
    discrepancy_type TEXT,
    notes TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS asset_action_history (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    actor_user_id TEXT NOT NULL,
    reason TEXT,
    before_json TEXT NOT NULL DEFAULT '{}',
    after_json TEXT NOT NULL DEFAULT '{}',
    request_context_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_asset_history_asset ON asset_action_history(asset_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS asset_register (
    id TEXT PRIMARY KEY,
    asset_number TEXT NOT NULL UNIQUE,
    managed_asset_id TEXT UNIQUE REFERENCES managed_assets(id),
    asset_name TEXT NOT NULL,
    acquisition_value_minor INTEGER NOT NULL DEFAULT 0,
    accumulated_depreciation_minor INTEGER NOT NULL DEFAULT 0,
    current_book_value_minor INTEGER NOT NULL DEFAULT 0,
    currency_code TEXT NOT NULL DEFAULT 'IDR',
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISPOSED', 'REVERSED')),
    as_of_date TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`
];

export const corporateAssetDropStatements = [
  'DROP TABLE IF EXISTS asset_register',
  'DROP TABLE IF EXISTS asset_action_history',
  'DROP TABLE IF EXISTS asset_audit_lines',
  'DROP TABLE IF EXISTS asset_audits',
  'DROP TABLE IF EXISTS asset_insurance_policies',
  'DROP TABLE IF EXISTS asset_maintenance_work_orders',
  'DROP TABLE IF EXISTS asset_custody_movements',
  'DROP TABLE IF EXISTS asset_assignments',
  'DROP TABLE IF EXISTS asset_number_sequences',
  'DROP TABLE IF EXISTS managed_assets',
  'DROP TABLE IF EXISTS employees',
  'DROP TABLE IF EXISTS departments'
];
