export const commercialMasterDataStatements = [
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    account_code TEXT NOT NULL UNIQUE,
    account_name TEXT NOT NULL,
    account_type TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    billing_address TEXT,
    payment_term_id TEXT REFERENCES payment_terms(id),
    credit_limit INTEGER CHECK (credit_limit IS NULL OR credit_limit >= 0),
    is_active INTEGER NOT NULL DEFAULT 1,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
    credit_status TEXT NOT NULL DEFAULT 'NORMAL',
    default_currency_code TEXT NOT NULL DEFAULT 'IDR',
    primary_contact_id TEXT,
    commercial_note TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_contacts (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    contact_name TEXT NOT NULL,
    role_title TEXT,
    email TEXT,
    phone TEXT,
    contact_type TEXT NOT NULL DEFAULT 'OTHER',
    is_primary INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_notes (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    note_type TEXT NOT NULL DEFAULT 'GENERAL',
    visibility TEXT NOT NULL DEFAULT 'INTERNAL',
    note TEXT NOT NULL,
    author_id TEXT,
    author_name TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_credit_actions (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    reason TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_audit_logs (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_contracts (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    contract_number TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    effective_from TEXT,
    effective_until TEXT,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    signed_date TEXT,
    document_id TEXT,
    renewal_status TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agents (
    id TEXT PRIMARY KEY,
    agent_code TEXT NOT NULL UNIQUE,
    agent_name TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    station_id TEXT REFERENCES stations(id),
    customer_account_id TEXT REFERENCES customers(id),
    responsible_personnel_id TEXT,
    primary_contact_id TEXT,
    booking_channel_code TEXT,
    default_currency_code TEXT NOT NULL DEFAULT 'IDR',
    operational_note TEXT,
    commission_basis_points INTEGER CHECK (commission_basis_points IS NULL OR commission_basis_points >= 0),
    contact_person TEXT,
    phone TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_contacts (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    contact_name TEXT NOT NULL,
    role_title TEXT,
    department TEXT,
    email TEXT,
    phone TEXT,
    contact_type TEXT NOT NULL DEFAULT 'OTHER',
    is_primary INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_commission_rules (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    commission_type TEXT NOT NULL DEFAULT 'PERCENTAGE',
    percentage_basis_points INTEGER CHECK (percentage_basis_points IS NULL OR percentage_basis_points BETWEEN 0 AND 10000),
    fixed_amount_minor TEXT,
    currency_code TEXT,
    basis_type TEXT NOT NULL DEFAULT 'BASE_FARE',
    service_type_id TEXT,
    route_id TEXT,
    rate_agreement_id TEXT,
    effective_from TEXT NOT NULL,
    effective_until TEXT,
    lifecycle_status TEXT NOT NULL DEFAULT 'DRAFT',
    priority INTEGER NOT NULL DEFAULT 100,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (effective_until IS NULL OR effective_until >= effective_from)
  )`,
  `CREATE TABLE IF NOT EXISTS agent_notes (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    note_type TEXT NOT NULL DEFAULT 'GENERAL',
    visibility TEXT NOT NULL DEFAULT 'INTERNAL',
    note TEXT NOT NULL,
    author_id TEXT,
    author_name TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_audit_logs (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_contracts (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    contract_number TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    effective_from TEXT,
    effective_until TEXT,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    signed_date TEXT,
    document_id TEXT,
    renewal_status TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS rate_cards (
    id TEXT PRIMARY KEY,
    rate_code TEXT NOT NULL UNIQUE,
    rate_name TEXT,
    service_type TEXT NOT NULL,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
    origin_station_id TEXT NOT NULL REFERENCES stations(id),
    destination_station_id TEXT NOT NULL REFERENCES stations(id),
    route_id TEXT REFERENCES routes(id),
    customer_id TEXT REFERENCES customers(id),
    agent_id TEXT REFERENCES agents(id),
    contract_id TEXT,
    aircraft_type TEXT,
    aircraft_type_id TEXT REFERENCES aircraft(id),
    currency_id TEXT NOT NULL REFERENCES currencies(id),
    tax_code_id TEXT REFERENCES tax_codes(id),
    base_rate INTEGER NOT NULL CHECK (base_rate >= 0),
    rate_unit TEXT NOT NULL,
    pricing_scope TEXT NOT NULL DEFAULT 'PUBLIC_COUNTER' CHECK (pricing_scope IN ('PUBLIC', 'PUBLIC_COUNTER', 'CUSTOMER_CONTRACT', 'CORPORATE_CONTRACT', 'AGENT_CONTRACT', 'CARGO_CONTRACT', 'CHARTER_CONTRACT', 'ROUTE', 'STATION_PAIR', 'INTERNAL')),
    booking_channel TEXT NOT NULL DEFAULT 'COUNTER' CHECK (booking_channel IN ('COUNTER', 'AGENT', 'CORPORATE', 'CARGO', 'CHARTER', 'WEBSITE', 'INTERNAL_OPERATIONS', 'API_PARTNER')),
    passenger_type TEXT CHECK (passenger_type IS NULL OR passenger_type IN ('ADULT', 'CHILD', 'INFANT')),
    cargo_price_basis TEXT CHECK (cargo_price_basis IS NULL OR cargo_price_basis IN ('ACTUAL_WEIGHT', 'VOLUME_WEIGHT', 'VOLUMETRIC_WEIGHT', 'CHARGEABLE_WEIGHT', 'PIECE', 'FLAT')),
    rate_priority INTEGER NOT NULL DEFAULT 100 CHECK (rate_priority >= 0),
    minimum_charge INTEGER CHECK (minimum_charge IS NULL OR minimum_charge >= 0),
    demo_usage_note TEXT,
    public_note TEXT,
    internal_pricing_note TEXT,
    effective_from TEXT NOT NULL,
    effective_to TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    rate_family_id TEXT,
    supersedes_rate_id TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    created_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (origin_station_id <> destination_station_id),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
  )`,
  `CREATE TABLE IF NOT EXISTS rate_booking_channels (
    id TEXT PRIMARY KEY,
    rate_card_id TEXT NOT NULL REFERENCES rate_cards(id) ON DELETE CASCADE,
    booking_channel_code TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    effective_until TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(rate_card_id, booking_channel_code, effective_from)
  )`,
  `CREATE TABLE IF NOT EXISTS rate_contract_links (
    id TEXT PRIMARY KEY,
    rate_card_id TEXT NOT NULL REFERENCES rate_cards(id) ON DELETE CASCADE,
    customer_id TEXT REFERENCES customers(id),
    contract_number TEXT NOT NULL,
    contract_name TEXT,
    effective_from TEXT,
    effective_until TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    rate_scope TEXT,
    document_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS rate_audit_logs (
    id TEXT PRIMARY KEY,
    rate_card_id TEXT NOT NULL REFERENCES rate_cards(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS contract_subsidy_programs (
    id TEXT PRIMARY KEY,
    program_code TEXT NOT NULL UNIQUE,
    program_name TEXT NOT NULL,
    sponsor_name TEXT NOT NULL,
    service_scope TEXT NOT NULL,
    route_scope TEXT,
    customer_id TEXT REFERENCES customers(id),
    contract_number TEXT,
    currency_code TEXT NOT NULL DEFAULT 'IDR',
    allocated_budget_minor INTEGER NOT NULL DEFAULT 0 CHECK (allocated_budget_minor >= 0),
    effective_from TEXT NOT NULL,
    effective_until TEXT,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
    renewal_status TEXT,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (effective_until IS NULL OR effective_until >= effective_from)
  )`,
  `CREATE TABLE IF NOT EXISTS contract_subsidy_consumptions (
    id TEXT PRIMARY KEY,
    program_id TEXT NOT NULL REFERENCES contract_subsidy_programs(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL,
    source_id TEXT,
    description TEXT NOT NULL,
    amount_minor INTEGER NOT NULL DEFAULT 0 CHECK (amount_minor >= 0),
    currency_code TEXT NOT NULL DEFAULT 'IDR',
    status TEXT NOT NULL DEFAULT 'RECOGNIZED',
    consumed_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS contract_subsidy_audit_logs (
    id TEXT PRIMARY KEY,
    program_id TEXT REFERENCES contract_subsidy_programs(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_customers_active ON customers(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_account_type ON customers(account_type)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_lifecycle_status ON customers(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_credit_status ON customers(credit_status)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_payment_term ON customers(payment_term_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customers_primary_contact ON customers(primary_contact_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_contacts_customer ON customer_contacts(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_contacts_primary ON customer_contacts(customer_id, is_primary)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_notes_customer ON customer_notes(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_credit_actions_customer ON customer_credit_actions(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_audit_logs_customer ON customer_audit_logs(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_contracts_customer ON customer_contracts(customer_id)`,
  `INSERT OR IGNORE INTO customer_contacts (
    id, customer_id, contact_name, role_title, email, phone, contact_type, is_primary, is_active, notes, created_at, updated_at
  )
  SELECT
    'customer-contact-' || id,
    id,
    contact_person,
    NULL,
    email,
    phone,
    'PRIMARY',
    1,
    1,
    NULL,
    created_at,
    updated_at
  FROM customers
  WHERE contact_person IS NOT NULL AND trim(contact_person) <> ''`,
  `UPDATE customers
  SET primary_contact_id = 'customer-contact-' || id
  WHERE primary_contact_id IS NULL
    AND contact_person IS NOT NULL
    AND trim(contact_person) <> ''`,
  `UPDATE customers
  SET lifecycle_status = CASE WHEN is_active = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END
  WHERE lifecycle_status IS NULL OR lifecycle_status = ''`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_active ON rate_cards(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_lifecycle ON rate_cards(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_effective ON rate_cards(effective_from, effective_to)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_service ON rate_cards(service_type)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_route ON rate_cards(route_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_station_pair ON rate_cards(origin_station_id, destination_station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_customer ON rate_cards(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_agent ON rate_cards(agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_contract ON rate_cards(contract_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_priority ON rate_cards(rate_priority)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_currency ON rate_cards(currency_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_cards_tax ON rate_cards(tax_code_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_booking_channels_rate ON rate_booking_channels(rate_card_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_booking_channels_code ON rate_booking_channels(booking_channel_code)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_contract_links_rate ON rate_contract_links(rate_card_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_contract_links_customer ON rate_contract_links(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_rate_audit_logs_rate ON rate_audit_logs(rate_card_id)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_programs_status ON contract_subsidy_programs(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_programs_customer ON contract_subsidy_programs(customer_id)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_programs_effective ON contract_subsidy_programs(effective_from, effective_until)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_consumptions_program ON contract_subsidy_consumptions(program_id)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_consumptions_source ON contract_subsidy_consumptions(source_type, source_id)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_consumptions_consumed_at ON contract_subsidy_consumptions(consumed_at)`,
  `CREATE INDEX IF NOT EXISTS idx_contract_subsidy_audit_logs_program ON contract_subsidy_audit_logs(program_id)`,
  `UPDATE rate_cards
  SET lifecycle_status = CASE WHEN is_active = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END
  WHERE lifecycle_status IS NULL OR lifecycle_status = ''`,
  `UPDATE rate_cards
  SET rate_family_id = id
  WHERE rate_family_id IS NULL OR rate_family_id = ''`,
  `INSERT OR IGNORE INTO rate_booking_channels (
    id, rate_card_id, booking_channel_code, effective_from, effective_until, status, created_at, updated_at
  )
  SELECT
    'rate-booking-channel-' || id,
    id,
    booking_channel,
    effective_from,
    effective_to,
    CASE WHEN is_active = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END,
    created_at,
    updated_at
  FROM rate_cards
  WHERE booking_channel IS NOT NULL AND trim(booking_channel) <> ''`,
  `CREATE INDEX IF NOT EXISTS idx_agents_type ON agents(agent_type)`,
  `CREATE INDEX IF NOT EXISTS idx_agents_lifecycle_status ON agents(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_agents_station ON agents(station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agents_customer_account ON agents(customer_account_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agents_primary_contact ON agents(primary_contact_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_contacts_agent ON agent_contacts(agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_contacts_primary ON agent_contacts(agent_id, is_primary)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_commission_rules_agent ON agent_commission_rules(agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_commission_rules_status ON agent_commission_rules(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_commission_rules_effective ON agent_commission_rules(agent_id, effective_from, effective_until)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_notes_agent ON agent_notes(agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_audit_logs_agent ON agent_audit_logs(agent_id)`,
  `CREATE INDEX IF NOT EXISTS idx_agent_contracts_agent ON agent_contracts(agent_id)`,
  `INSERT OR IGNORE INTO agent_contacts (
    id, agent_id, contact_name, role_title, department, email, phone, contact_type, is_primary, is_active, notes, created_at, updated_at
  )
  SELECT
    'agent-contact-' || id,
    id,
    contact_person,
    NULL,
    NULL,
    NULL,
    phone,
    'PRIMARY',
    1,
    1,
    NULL,
    created_at,
    updated_at
  FROM agents
  WHERE contact_person IS NOT NULL AND trim(contact_person) <> ''`,
  `UPDATE agents
  SET primary_contact_id = 'agent-contact-' || id
  WHERE primary_contact_id IS NULL
    AND contact_person IS NOT NULL
    AND trim(contact_person) <> ''`,
  `INSERT OR IGNORE INTO agent_commission_rules (
    id, agent_id, commission_type, percentage_basis_points, fixed_amount_minor, currency_code,
    basis_type, service_type_id, route_id, rate_agreement_id, effective_from, effective_until,
    lifecycle_status, priority, version, created_at, updated_at
  )
  SELECT
    'agent-commission-rule-' || id,
    id,
    'PERCENTAGE',
    COALESCE(commission_basis_points, 0),
    NULL,
    default_currency_code,
    'BASE_FARE',
    NULL,
    NULL,
    NULL,
    substr(created_at, 1, 10),
    NULL,
    'ACTIVE',
    100,
    1,
    created_at,
    updated_at
  FROM agents
  WHERE commission_basis_points IS NOT NULL`
];

export const commercialMasterDataDropStatements = [
  'DROP TABLE IF EXISTS contract_subsidy_audit_logs',
  'DROP TABLE IF EXISTS contract_subsidy_consumptions',
  'DROP TABLE IF EXISTS contract_subsidy_programs',
  'DROP TABLE IF EXISTS rate_audit_logs',
  'DROP TABLE IF EXISTS rate_contract_links',
  'DROP TABLE IF EXISTS rate_booking_channels',
  'DROP TABLE IF EXISTS rate_cards',
  'DROP TABLE IF EXISTS agent_contracts',
  'DROP TABLE IF EXISTS agent_audit_logs',
  'DROP TABLE IF EXISTS agent_notes',
  'DROP TABLE IF EXISTS agent_commission_rules',
  'DROP TABLE IF EXISTS agent_contacts',
  'DROP TABLE IF EXISTS agents',
  'DROP TABLE IF EXISTS customer_contracts',
  'DROP TABLE IF EXISTS customer_audit_logs',
  'DROP TABLE IF EXISTS customer_credit_actions',
  'DROP TABLE IF EXISTS customer_notes',
  'DROP TABLE IF EXISTS customer_contacts',
  'DROP TABLE IF EXISTS customers'
];
