export const operationsMasterDataStatements = [
  `CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,
    station_code TEXT NOT NULL UNIQUE,
    station_name TEXT NOT NULL,
    iata_code TEXT,
    icao_code TEXT,
    airport_type TEXT,
    operational_status TEXT NOT NULL DEFAULT 'ACTIVE',
    city TEXT,
    province TEXT,
    country_code TEXT,
    timezone TEXT NOT NULL DEFAULT 'Asia/Jayapura',
    latitude REAL,
    longitude REAL,
    elevation_ft INTEGER,
    surface_type TEXT,
    runway_length_m INTEGER,
    runway_width_m INTEGER,
    station_pic_name TEXT,
    station_pic_phone TEXT,
    operational_notes TEXT,
    is_remote_station INTEGER NOT NULL DEFAULT 0,
    low_connectivity_mode INTEGER NOT NULL DEFAULT 0,
    has_fuel_service INTEGER NOT NULL DEFAULT 0,
    has_handling_service INTEGER NOT NULL DEFAULT 0,
    has_parking_service INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aircraft (
    id TEXT PRIMARY KEY,
    registration_number TEXT NOT NULL UNIQUE,
    serial_number TEXT,
    aircraft_type TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    model TEXT NOT NULL,
    fleet_code TEXT,
    passenger_capacity INTEGER NOT NULL CHECK (passenger_capacity >= 0),
    cargo_capacity_kg INTEGER NOT NULL CHECK (cargo_capacity_kg >= 0),
    fuel_type TEXT NOT NULL,
    operational_status TEXT NOT NULL DEFAULT 'ACTIVE',
    serviceability_status TEXT NOT NULL,
    base_station_id TEXT REFERENCES stations(id),
    current_station_id TEXT REFERENCES stations(id),
    default_capacity_profile_id TEXT REFERENCES flight_capacity_profiles(id),
    last_maintenance_check_at TEXT,
    next_maintenance_due_at TEXT,
    serviceability_note TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS routes (
    id TEXT PRIMARY KEY,
    route_code TEXT NOT NULL UNIQUE,
    origin_station_id TEXT NOT NULL REFERENCES stations(id),
    destination_station_id TEXT NOT NULL REFERENCES stations(id),
    estimated_duration_minutes INTEGER NOT NULL CHECK (estimated_duration_minutes > 0),
    distance_km INTEGER NOT NULL CHECK (distance_km > 0),
    operational_notes TEXT,
    restriction_level TEXT NOT NULL DEFAULT 'NONE' CHECK (restriction_level IN ('NONE', 'ADVISORY', 'BLOCKING')),
    restriction_note TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (origin_station_id, destination_station_id),
    CHECK (origin_station_id <> destination_station_id)
  )`,
  `CREATE TABLE IF NOT EXISTS flight_schedule_templates (
    id TEXT PRIMARY KEY,
    template_code TEXT NOT NULL UNIQUE,
    route_id TEXT NOT NULL REFERENCES routes(id),
    service_type_id TEXT NOT NULL REFERENCES flight_service_types(id),
    default_aircraft_id TEXT REFERENCES aircraft(id),
    capacity_profile_id TEXT REFERENCES flight_capacity_profiles(id),
    operating_days TEXT NOT NULL,
    departure_time_local TEXT NOT NULL,
    arrival_time_local TEXT NOT NULL,
    arrival_day_offset INTEGER NOT NULL DEFAULT 0 CHECK (arrival_day_offset >= 0),
    booking_open_minutes_before INTEGER NOT NULL DEFAULT 4320 CHECK (booking_open_minutes_before >= 0),
    booking_open_hours_before INTEGER NOT NULL DEFAULT 72 CHECK (booking_open_hours_before >= 0),
    booking_close_minutes_before INTEGER NOT NULL DEFAULT 60 CHECK (booking_close_minutes_before >= 0),
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (lifecycle_status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    effective_from TEXT,
    effective_until TEXT,
    schedule_note TEXT,
    internal_operational_note TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (booking_close_minutes_before < booking_open_minutes_before)
  )`,
  `CREATE TABLE IF NOT EXISTS schedule_template_audit_logs (
    id TEXT PRIMARY KEY,
    template_id TEXT NOT NULL REFERENCES flight_schedule_templates(id),
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS flight_capacity_profiles (
    id TEXT PRIMARY KEY,
    profile_code TEXT NOT NULL UNIQUE,
    profile_name TEXT NOT NULL DEFAULT '',
    aircraft_id TEXT NOT NULL REFERENCES aircraft(id),
    route_id TEXT NOT NULL REFERENCES routes(id),
    service_type_id TEXT NOT NULL REFERENCES flight_service_types(id),
    seat_capacity INTEGER NOT NULL CHECK (seat_capacity >= 0),
    cargo_capacity_kg INTEGER NOT NULL CHECK (cargo_capacity_kg >= 0),
    reserved_seat_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_seat_count >= 0),
    reserved_cargo_kg INTEGER NOT NULL DEFAULT 0 CHECK (reserved_cargo_kg >= 0),
    capacity_note TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (aircraft_id, route_id, service_type_id),
    CHECK (reserved_seat_count <= seat_capacity),
    CHECK (reserved_cargo_kg <= cargo_capacity_kg)
  )`,
  `CREATE TABLE IF NOT EXISTS departments (
    id TEXT PRIMARY KEY,
    department_code TEXT NOT NULL UNIQUE,
    department_name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS crews (
    id TEXT PRIMARY KEY,
    employee_code TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    gender TEXT,
    date_of_birth TEXT,
    nationality_code TEXT,
    phone TEXT,
    email TEXT,
    crew_role TEXT NOT NULL,
    license_type TEXT,
    license_number TEXT,
    license_expiry_date TEXT,
    medical_expiry_date TEXT,
    base_station_id TEXT REFERENCES stations(id),
    availability_status TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK (availability_status IN ('AVAILABLE', 'ON_DUTY', 'ASSIGNED_OTHER_FLIGHT', 'ON_LEAVE', 'UNAVAILABLE')),
    duty_station_id TEXT REFERENCES stations(id),
    readiness_note TEXT,
    unit TEXT NOT NULL,
    department_id TEXT REFERENCES departments(id),
    supervisor_personnel_id TEXT REFERENCES crews(id),
    employment_status TEXT NOT NULL,
    lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
    version INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS personnel_licenses (
    id TEXT PRIMARY KEY,
    personnel_id TEXT NOT NULL REFERENCES crews(id),
    license_type TEXT NOT NULL,
    license_number TEXT NOT NULL,
    issuing_authority TEXT,
    issue_date TEXT,
    expiry_date TEXT,
    is_primary INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED', 'SUPERSEDED')),
    document_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS personnel_medical_certificates (
    id TEXT PRIMARY KEY,
    personnel_id TEXT NOT NULL REFERENCES crews(id),
    certificate_type TEXT NOT NULL,
    certificate_number TEXT,
    issue_date TEXT,
    expiry_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED', 'SUPERSEDED')),
    restrictions TEXT,
    issuing_authority TEXT,
    document_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS personnel_qualifications (
    id TEXT PRIMARY KEY,
    personnel_id TEXT NOT NULL REFERENCES crews(id),
    qualification_type TEXT NOT NULL,
    reference_type TEXT,
    reference_id TEXT,
    issued_at TEXT,
    expires_at TEXT,
    status TEXT NOT NULL DEFAULT 'VALID' CHECK (status IN ('VALID', 'EXPIRING_SOON', 'EXPIRED', 'SUSPENDED')),
    notes TEXT,
    document_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS personnel_notes (
    id TEXT PRIMARY KEY,
    personnel_id TEXT NOT NULL REFERENCES crews(id),
    note_type TEXT NOT NULL DEFAULT 'GENERAL' CHECK (note_type IN ('OPERATIONAL', 'HR', 'TRAINING', 'SAFETY', 'GENERAL')),
    visibility TEXT NOT NULL DEFAULT 'INTERNAL' CHECK (visibility IN ('INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    note_text TEXT NOT NULL,
    author_id TEXT,
    author_name TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS personnel_audit_logs (
    id TEXT PRIMARY KEY,
    personnel_id TEXT NOT NULL REFERENCES crews(id),
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_name TEXT,
    changed_fields TEXT NOT NULL DEFAULT '[]',
    metadata TEXT,
    request_id TEXT,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS flight_reasons (
    id TEXT PRIMARY KEY,
    reason_code TEXT NOT NULL UNIQUE,
    reason_name TEXT NOT NULL DEFAULT '',
    reason_type TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    requires_note INTEGER NOT NULL DEFAULT 0,
    affects_operational_kpi INTEGER NOT NULL DEFAULT 1,
    affects_finance_review INTEGER NOT NULL DEFAULT 0,
    dashboard_severity TEXT NOT NULL DEFAULT 'WARNING' CHECK (dashboard_severity IN ('INFO', 'WARNING', 'CRITICAL')),
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_aircraft_active ON aircraft(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_stations_active ON stations(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_routes_active ON routes(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_active ON flight_schedule_templates(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_lifecycle ON flight_schedule_templates(lifecycle_status)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_effective ON flight_schedule_templates(effective_from, effective_until)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_route ON flight_schedule_templates(route_id)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_aircraft ON flight_schedule_templates(default_aircraft_id)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_templates_capacity_profile ON flight_schedule_templates(capacity_profile_id)`,
  `CREATE INDEX IF NOT EXISTS idx_schedule_template_audit_template_id ON schedule_template_audit_logs(template_id)`,
  `CREATE INDEX IF NOT EXISTS idx_capacity_profiles_active ON flight_capacity_profiles(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_crews_active ON crews(is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_crews_base_station ON crews(base_station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_crews_duty_station ON crews(duty_station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_crews_department ON crews(department_id)`,
  `CREATE INDEX IF NOT EXISTS idx_crews_supervisor ON crews(supervisor_personnel_id)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_licenses_personnel ON personnel_licenses(personnel_id)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_licenses_expiry ON personnel_licenses(expiry_date)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_personnel_primary_active_license ON personnel_licenses(personnel_id) WHERE is_primary = 1 AND status = 'ACTIVE'`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_medical_personnel ON personnel_medical_certificates(personnel_id)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_medical_expiry ON personnel_medical_certificates(expiry_date)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_qualifications_personnel ON personnel_qualifications(personnel_id)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_qualifications_expiry ON personnel_qualifications(expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_notes_personnel ON personnel_notes(personnel_id)`,
  `CREATE INDEX IF NOT EXISTS idx_personnel_audit_personnel ON personnel_audit_logs(personnel_id)`
];

export const operationsMasterDataDropStatements = [
  'DROP TABLE IF EXISTS personnel_audit_logs',
  'DROP TABLE IF EXISTS personnel_notes',
  'DROP TABLE IF EXISTS personnel_qualifications',
  'DROP TABLE IF EXISTS personnel_medical_certificates',
  'DROP TABLE IF EXISTS personnel_licenses',
  'DROP TABLE IF EXISTS crews',
  'DROP TABLE IF EXISTS stations',
  'DROP TABLE IF EXISTS aircraft',
  'DROP TABLE IF EXISTS routes',
  'DROP TABLE IF EXISTS flight_schedule_templates',
  'DROP TABLE IF EXISTS flight_capacity_profiles',
  'DROP TABLE IF EXISTS departments',
  'DROP TABLE IF EXISTS flight_reasons'
];
