export const demoRoles = [
  'Demo Admin',
  'Director',
  'OCC',
  'Station Admin',
  'Finance Reviewer',
  'Maintenance Manager',
  'Inventory Controller',
  'HR Staff',
  'HR Manager',
  'Chief of Pilot',
  'Employee'
] as const;

export type DemoRole = (typeof demoRoles)[number];

export const defaultDemoRole: DemoRole = 'Demo Admin';

export const demoRoleActorIds: Record<DemoRole, string> = {
  'Demo Admin': 'USR-ADMIN',
  Director: 'USR-DIRECTOR',
  OCC: 'USR-001',
  'Station Admin': 'USR-STATION-ADMIN',
  'Finance Reviewer': 'USR-FINANCE-REVIEWER',
  'Maintenance Manager': 'USR-MAINTENANCE-MANAGER',
  'Inventory Controller': 'USR-INVENTORY-CONTROLLER',
  'HR Staff': 'USR-HR-STAFF',
  'HR Manager': 'USR-HR-MANAGER',
  'Chief of Pilot': 'USR-CHIEF-PILOT',
  Employee: 'USR-EMPLOYEE'
};

export const demoRoleStationScopes: Record<DemoRole, readonly string[]> = {
  'Demo Admin': ['ALL'],
  Director: ['ALL'],
  OCC: ['DJJ', 'WMX'],
  'Station Admin': ['WMX'],
  'Finance Reviewer': ['ALL'],
  'Maintenance Manager': ['DJJ'],
  'Inventory Controller': ['ALL'],
  'HR Staff': ['ALL'],
  'HR Manager': ['ALL'],
  'Chief of Pilot': ['ALL'],
  Employee: ['ALL']
};

export const demoRolePermissions: Record<DemoRole, readonly string[]> = {
  'Demo Admin': ['*'],
  Director: [
    'platform.dashboard.view',
    'flight_request.read',
    'flight_request.approve',
    'flight.read',
    'flight.approve',
    'flight.closure.create',
    'station.cost.approve',
    'ticketing.refund.decide',
    'finance.invoice.read',
    'finance.accounting.read',
    'finance.accounting.post',
    'finance.payment.record',
    'document.read',
    'document.verify',
    'inventory.read',
    'inventory.po.approve',
    'inventory.valuation.read',
    'asset.read',
    'asset.finance.read',
    'master_data.read',
    'hris.employee.read',
    'hris.org.read',
    'hris.kpi.read',
    'hris.payroll.read'
  ],
  OCC: [
    'platform.dashboard.view',
    'flight_request.read',
    'flight_request.create',
    'flight.read',
    'flight.create.direct',
    'flight.readiness.evaluate',
    'flight.schedule',
    'flight.movement.update',
    'flight.exception.update',
    'flight.manifest.update',
    'flight.fuel.update',
    'ticketing.sales.open',
    'ticketing.operation.update',
    'document.read',
    'document.upload',
    'inventory.read',
    'master_data.read'
  ],
  'Station Admin': [
    'platform.dashboard.view',
    'flight.read',
    'flight.readiness.evaluate',
    'flight.movement.update',
    'flight.manifest.update',
    'flight.fuel.update',
    'station.operation.update',
    'ticketing.operation.update',
    'document.read',
    'document.upload',
    'inventory.read',
    'asset.read',
    'asset.assign',
    'asset.move',
    'master_data.read',
    'hris.attendance.read',
    'hris.attendance.manage',
    'hris.schedule.read'
  ],
  'Finance Reviewer': [
    'platform.dashboard.view',
    'flight.read',
    'finance.invoice.read',
    'finance.invoice.approve',
    'finance.accounting.read',
    'finance.accounting.post',
    'finance.handoff.process',
    'finance.payment.record',
    'document.read',
    'document.verify',
    'inventory.read',
    'asset.read',
    'asset.finance.read',
    'inventory.valuation.read',
    'hris.payroll.read'
  ],
  'Maintenance Manager': [
    'platform.dashboard.view',
    'flight.read',
    'maintenance.handoff.update',
    'document.read',
    'document.verify',
    'inventory.read',
    'inventory.procurement.request',
    'inventory.issue',
    'inventory.repair.manage',
    'asset.read',
    'asset.maintenance.manage'
  ],
  'Inventory Controller': [
    'platform.dashboard.view',
    'inventory.read',
    'inventory.catalog.manage',
    'inventory.procurement.request',
    'inventory.procurement.manage',
    'inventory.receive',
    'inventory.transfer',
    'inventory.adjust',
    'inventory.count',
    'inventory.issue',
    'inventory.repair.manage',
    'inventory.valuation.read',
    'asset.read',
    'document.read',
    'document.upload'
  ],
  'HR Staff': [
    'platform.dashboard.view',
    'hris.employee.read',
    'hris.employee.manage',
    'hris.employee.import',
    'hris.attendance.read',
    'hris.attendance.manage',
    'hris.leave.read',
    'hris.leave.approve',
    'hris.overtime.approve',
    'hris.certification.read',
    'hris.certification.manage',
    'hris.schedule.read',
    'hris.schedule.manage',
    'hris.payroll.read',
    'hris.payroll.calculate',
    'hris.allowance.read',
    'hris.allowance.manage',
    'hris.recruitment.manage',
    'hris.kpi.read',
    'hris.kpi.manage',
    'hris.org.read',
    'hris.self_service.read',
    'master_data.read'
  ],
  'HR Manager': [
    'platform.dashboard.view',
    'hris.employee.read',
    'hris.employee.manage',
    'hris.employee.import',
    'hris.attendance.read',
    'hris.attendance.manage',
    'hris.leave.read',
    'hris.leave.approve',
    'hris.overtime.approve',
    'hris.certification.read',
    'hris.certification.manage',
    'hris.schedule.read',
    'hris.schedule.manage',
    'hris.payroll.read',
    'hris.payroll.calculate',
    'hris.payroll.approve',
    'hris.payroll.journal',
    'hris.allowance.read',
    'hris.allowance.manage',
    'hris.recruitment.manage',
    'hris.kpi.read',
    'hris.kpi.assess',
    'hris.kpi.manage',
    'hris.org.read',
    'hris.self_service.read',
    'master_data.read',
    'finance.accounting.read'
  ],
  'Chief of Pilot': [
    'platform.dashboard.view',
    'flight.read',
    'hris.employee.read',
    'hris.certification.read',
    'hris.certification.manage',
    'hris.schedule.read',
    'hris.schedule.manage',
    'hris.kpi.read',
    'hris.kpi.assess',
    'hris.leave.read',
    'hris.leave.approve',
    'hris.overtime.approve',
    'hris.org.read',
    'hris.self_service.read',
    'master_data.read'
  ],
  Employee: [
    'platform.dashboard.view',
    'hris.self_service.read',
    'hris.leave.request',
    'hris.overtime.request',
    'hris.attendance.checkin'
  ]
};
