import type { CargoBookingDto } from '#shared/features/ticketing/cargo';
import type { PassengerTicketDto } from '#shared/features/ticketing/passenger';

type DocumentRow = [label: string, value: string];

async function saveTicketingDocument(
  title: string,
  documentId: string,
  rows: DocumentRow[],
  amount: number,
  currencyCode: string
) {
  const { jsPDF } = await import('jspdf');
  const document = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' });
  document.setFillColor(16, 76, 111);
  document.rect(0, 0, 148, 30, 'F');
  document.setTextColor(255, 255, 255);
  document.setFontSize(17);
  document.text('ASSOCIATED MISSION AVIATION', 12, 13);
  document.setFontSize(10);
  document.text(title, 12, 22);
  document.setTextColor(24, 38, 52);
  document.setFontSize(9);
  let y = 42;
  for (const [label, value] of rows) {
    document.setTextColor(98, 112, 126);
    document.text(label.toUpperCase(), 12, y);
    document.setTextColor(24, 38, 52);
    document.text(value || '-', 52, y);
    document.setDrawColor(225, 231, 236);
    document.line(12, y + 3, 136, y + 3);
    y += 11;
  }
  document.setFillColor(238, 245, 248);
  document.roundedRect(12, y + 2, 124, 20, 2, 2, 'F');
  document.setFontSize(9);
  document.text('TOTAL', 18, y + 10);
  document.setFontSize(14);
  document.text(
    new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: currencyCode,
      maximumFractionDigits: 0
    }).format(amount),
    18,
    y + 18
  );
  document.setFontSize(8);
  document.setTextColor(98, 112, 126);
  document.text('Demo document generated by AMA Interface', 12, 198);
  document.save(`${documentId}.pdf`);
}

export function downloadPassengerTicket(ticket: PassengerTicketDto) {
  return saveTicketingDocument(
    'PASSENGER TICKET RECEIPT',
    ticket.id,
    [
      ['Ticket number', ticket.id],
      ['Passenger', ticket.passengerName],
      ['Flight', `${ticket.flightNumber} / ${ticket.originCode} -> ${ticket.destinationCode}`],
      ['Departure', new Date(ticket.scheduledDeparture).toLocaleString('id-ID')],
      ['Seat', ticket.seatNumber],
      ['Document', `${ticket.documentType} ${ticket.documentNumber}`],
      ['Payment', ticket.paymentStatus],
      ['Check-in', ticket.checkInStatus]
    ],
    ticket.ticketPrice,
    ticket.currencyCode
  );
}

export function downloadCargoWaybill(booking: CargoBookingDto) {
  return saveTicketingDocument(
    'CARGO AIR WAYBILL',
    booking.id,
    [
      ['AWB number', booking.id],
      ['Sender', booking.senderName],
      ['Receiver', booking.receiverName],
      ['Flight', `${booking.flightNumber} / ${booking.originCode} -> ${booking.destinationCode}`],
      ['Departure', new Date(booking.scheduledDeparture).toLocaleString('id-ID')],
      ['Description', booking.description],
      ['Chargeable weight', `${booking.chargeableWeightKg} kg`],
      ['Payment', booking.paymentStatus],
      ['Delivery', booking.status]
    ],
    booking.totalTariff,
    booking.currencyCode
  );
}
